#!/usr/bin/env bash
# Install Nginx and configure it on my Web-01 server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
