#!/usr/bin/env bash
# Bash script that configures Nginx server with a custom http header
sudo apt-get -y update
sudo apt-get install -y nginx
sudo sed -i '11i\add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf
sudo service nginx start
