#!/usr/bin/env bash
#Traps a sigterm signal and echo I am invincible
#Otherwise print To infinity and beyond indefinitely
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done

